blogger_blog_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET

# src/Blogger/BlogBundle/Resources/config/routing.yml
blogger_blog_about:
    pattern:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET

# src/Blogger/BlogBundle/Resources/config/routing.yml
blogger_blog_contact:
    pattern:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST