blogger_blog_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET

# src/Blogger/BlogBundle/Resources/config/routing.yml
blogger_blog_about:
    pattern:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET

# src/Blogger/BlogBundle/Resources/config/routing.yml
blogger_blog_contact:
    pattern:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST

BloggerBlogBundle_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing/blog.yml"
    prefix:   /blog

BloggerBlogBundle_comment:
    resource: "@BloggerBlogBundle/Resources/config/routing/comment.yml"
    prefix:   /comment
